### ISSUE TITLE
Jinja templates in playbooks not supported?

### ISSUE THREAD

**Issue by jacobweber** [shaded-enmity/ansible-schema-generator#7]
Does this schema allow you to use [templated variables](https://docs.ansible.com/ansible/latest/user_guide/playbooks_variables.html#using-variables-with-jinja2) in your YAML? For example, when I validate this yaml file using http://json.schemastore.org/ansible-stable-2.5:

```
---
- name: test
  yum:
    name: foo
    state: "{{ bar }}"
```

on the last line, it says `Value is not accepted. Valid values: "absent", "installed", "latest", "present", "removed".`
